version: "3.9"
services:
  database:
    image: postgres:14.4
    container_name: docker-service-backend
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - volumen-db:/docker-entrypoint-initdb.d/:rw
volumes:
  volumen-db:
